// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marble.proto

package myProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Marble struct {
	ObjectType           string   `protobuf:"bytes,1,opt,name=ObjectType,proto3" json:"ObjectType,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Color                string   `protobuf:"bytes,3,opt,name=Color,proto3" json:"Color,omitempty"`
	Size                 int32    `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Marble) Reset()         { *m = Marble{} }
func (m *Marble) String() string { return proto.CompactTextString(m) }
func (*Marble) ProtoMessage()    {}
func (*Marble) Descriptor() ([]byte, []int) {
	return fileDescriptor_marble_d170778997dd73d6, []int{0}
}
func (m *Marble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Marble.Unmarshal(m, b)
}
func (m *Marble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Marble.Marshal(b, m, deterministic)
}
func (dst *Marble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Marble.Merge(dst, src)
}
func (m *Marble) XXX_Size() int {
	return xxx_messageInfo_Marble.Size(m)
}
func (m *Marble) XXX_DiscardUnknown() {
	xxx_messageInfo_Marble.DiscardUnknown(m)
}

var xxx_messageInfo_Marble proto.InternalMessageInfo

func (m *Marble) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *Marble) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Marble) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Marble) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Marble) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type Payload struct {
	AssetType            string   `protobuf:"bytes,1,opt,name=AssetType,proto3" json:"AssetType,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty"`
	AssetAddress         string   `protobuf:"bytes,3,opt,name=AssetAddress,proto3" json:"AssetAddress,omitempty"`
	PayloadData          *any.Any `protobuf:"bytes,4,opt,name=PayloadData,proto3" json:"PayloadData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_marble_d170778997dd73d6, []int{1}
}
func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (dst *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(dst, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetAssetType() string {
	if m != nil {
		return m.AssetType
	}
	return ""
}

func (m *Payload) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Payload) GetAssetAddress() string {
	if m != nil {
		return m.AssetAddress
	}
	return ""
}

func (m *Payload) GetPayloadData() *any.Any {
	if m != nil {
		return m.PayloadData
	}
	return nil
}

func init() {
	proto.RegisterType((*Marble)(nil), "myProto.marble")
	proto.RegisterType((*Payload)(nil), "myProto.payload")
}

func init() { proto.RegisterFile("marble.proto", fileDescriptor_marble_d170778997dd73d6) }

var fileDescriptor_marble_d170778997dd73d6 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0x36, 0x29, 0x9d, 0xf6, 0x34, 0x14, 0x59, 0x45, 0xa4, 0xe4, 0xd4, 0x53, 0x0a,
	0x0a, 0xde, 0x83, 0x9e, 0x6d, 0x89, 0xfe, 0x81, 0x4d, 0x33, 0x96, 0x48, 0x92, 0x09, 0xbb, 0x2b,
	0xb2, 0xe2, 0x3f, 0xf1, 0xcf, 0x4a, 0x66, 0x23, 0xc6, 0xdb, 0x7b, 0x6f, 0xbe, 0xe1, 0x0d, 0x03,
	0xab, 0x56, 0x9b, 0xb2, 0xa1, 0xac, 0x37, 0xec, 0x18, 0xe7, 0xad, 0x3f, 0x0c, 0xe2, 0xea, 0xf2,
	0xc4, 0x7c, 0x6a, 0x68, 0x27, 0x71, 0xf9, 0xfe, 0xba, 0xd3, 0x9d, 0x0f, 0x4c, 0xfa, 0x05, 0x49,
	0xd8, 0xc1, 0x1b, 0x80, 0x7d, 0xf9, 0x46, 0x47, 0xf7, 0xe2, 0x7b, 0x52, 0xd1, 0x26, 0xda, 0x2e,
	0x8a, 0x49, 0x82, 0x08, 0xb3, 0x27, 0xdd, 0x92, 0x3a, 0x93, 0x89, 0x68, 0x5c, 0x43, 0xfc, 0xc0,
	0x0d, 0x1b, 0x75, 0x2e, 0x61, 0x30, 0x03, 0xf9, 0x5c, 0x7f, 0x92, 0x9a, 0x6d, 0xa2, 0x6d, 0x5c,
	0x88, 0x1e, 0xc8, 0xfd, 0x47, 0x47, 0x46, 0xc5, 0x81, 0x14, 0x93, 0x7e, 0x47, 0x30, 0xef, 0xb5,
	0x6f, 0x58, 0x57, 0x78, 0x0d, 0x8b, 0xdc, 0x5a, 0x9a, 0xd6, 0xff, 0x05, 0x78, 0x01, 0x49, 0x7e,
	0x74, 0x35, 0x77, 0x63, 0xff, 0xe8, 0x30, 0x85, 0x95, 0x40, 0x79, 0x55, 0x19, 0xb2, 0x76, 0x3c,
	0xe4, 0x5f, 0x86, 0xf7, 0xb0, 0x3c, 0x84, 0x92, 0x47, 0xed, 0xb4, 0x9c, 0xb5, 0xbc, 0x5d, 0x67,
	0xe1, 0x29, 0xd9, 0xef, 0x53, 0xb2, 0xbc, 0xf3, 0xc5, 0x14, 0x2c, 0x13, 0x19, 0xdd, 0xfd, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x22, 0x2f, 0xec, 0x09, 0x56, 0x01, 0x00, 0x00,
}
